### ISSUE TITLE
TODO with plain list checkboxes, does this functionality exist?

### ISSUE THREAD

**Issue by yangnom** [alphapapa/org-super-agenda#121]
It has always been my agenda view dream to have the ability to have a TODO heading with a plain list with checkboxes that shows the TODO heading and _only_ the next (topmost) plain list checkbox item.

Basically I want this
```
* Organize life
  1. [x] Apply for job
  2. [x] Ace interview
  3. [ ] Get used to new job
  4. [ ] get new friends
```

to give me a section in my org-super-agenda view that looks like this
```
* Organize life
  3. [ ] Ace interview
```

Is this possible?  I've looked around for things about children and what not, but I'm not sure if what I'm describing is even possible, let alone how I'd go about achieving it.  Thank you.

**Comment by alphapapa** [comment]
Hello,

That is an interesting idea, but it's not related to this package, because all `org-super-agenda` does is group the output of Org Agenda and `org-ql` commands.

If you want to implement something like that, it would probably be best implemented using `org-ql` queries with a custom `action` function that returns the string you showed.

If you want to discuss this, please post it on reddit.com/r/orgmode, where others can contribute to the discussion.  Feel free to tag me in the post as `/u/github-alphapapa`.
